[env:esp32_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
board_build.flash_mode = dio
upload_flags = 
    --no-stub
build_flags =
    -D CONFIG_TARGET_ESP32_C3